@prefix coconut: <http://myontology.org/ontology#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dct: <http://purl.org/dc/terms/> .

coconut:ChemicalMetaClass rdf:type rdfs:Class ;
  rdfs:subClassOf owl:Thing ;
  rdfs:label "Chemical Meta Class"@en ;
  rdfs:comment "All chemical classes inherit from this class"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:ChemicalSuperClass rdf:type rdfs:Class ;
  rdfs:subClassOf coconut:ChemicalMetaClass ;
  rdfs:label "Chemical Super Class"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:ChemicalClass rdf:type rdfs:Class ;
  rdfs:subClassOf coconut:ChemicalSuperClass ;
  rdfs:label "Chemical Class"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:ChemicalSubClass rdf:type rdfs:Class ;
  rdfs:subClassOf coconut:ChemicalClass ;
  rdfs:label "Chemical Subclass"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:ChemicalLeafClass rdf:type rdfs:Class ;
  rdfs:subClassOf coconut:ChemicalSubClass ;
  rdfs:label "Chemical Leaf Class"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:Molecule rdf:type coconut:ChemicalMetaClass ;
  rdfs:label "Molecule"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:MolecularProperties rdf:type rdfs:Class ;
  rdfs:subClassOf owl:Thing ;
  rdfs:label "Molecular Properties"@en ;
  rdfs:comment "This is just a helper class for better structuring"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:MolecularDescriptors rdf:type rdfs:Class ;
  rdfs:subClassOf owl:Thing ;
  rdfs:label "Molecular Descriptors"@en ;
  rdfs:comment "This is just a helper class for better structuring"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:Reference rdf:type rdfs:Class ;
  rdfs:subClassOf owl:Thing ;
  rdfs:label "Reference"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:MolecularFormula rdf:type rdfs:Class ;
  rdfs:subClassOf owl:Thing ;
  rdfs:label "Molecular Formula"@en ;
  dct:issued "2022-06-07"^^xsd:date ;
.

coconut:molecularProperties rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range coconut:MolecularProperties ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Molecular Properties"@en
.

coconut:molecularDescriptors rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range coconut:MolecularDescriptors ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Molecular Descriptors"@en
.

coconut:molecularFormula rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range coconut:MolecularFormula ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Molecular Formula"@en
.

coconut:reference rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range coconut:Reference ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Reference"@en
.

coconut:name rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Molecule Name"@en
.

coconut:smile rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "SMILE"@en
.

coconut:inChI rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "InChI"@en
.

coconut:iupacName rdf:type owl:DatatypeProperty;
  rdfs:domain :Molecule ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "IUPAC Name"@en
.

coconut:bondCount rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularProperties ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issed "2022-06-07"^^xsd:date ;
  rdfs:label "Bond Count"@en
.

coconut:minNumberOfRings rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularProperties ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issed "2022-06-07"^^xsd:date ;
  rdfs:label "Minimum Number of Rings"@en
.

coconut:maxNumberOfRings rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularProperties ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issed "2022-06-07"^^xsd:date ;
  rdfs:label "Maximum Number of Rings"@en
.


coconut:doi rdf:type owl:DatatypeProperty;
  rdfs:domain :Reference ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "DOI"@en
.

coconut:title rdf:type owl:DatatypeProperty;
  rdfs:domain :Reference ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Title"@en
.

coconut:author rdf:type owl:DatatypeProperty;
  rdfs:domain :Reference ;
  rdfs:range xsd:string ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Author"@en
.

coconut:year rdf:type owl:DatatypeProperty;
  rdfs:domain :Reference ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Year"@en
.


coconut:molWeight rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularFormula ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Molecular Weight"@en
.

coconut:totalAtomNumber rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularFormula ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Total Number of Atoms"@en
.

coconut:heavyAtomNumber rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularFormula ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Number of Heavy Atoms"@en
.

coconut:numberOfCarbons rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularFormula ;
  rdfs:range xsd:nonNegativeInteger ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Number of Carbon Atoms"@en
.


coconut:Alogp rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Alogp"@en
.

coconut:Alogp2 rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Alogp2"@en
.

coconut:Apol rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label "Sum of the atomic polarizabilities"@en
.

coconut:Bpol rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:EccentricConnectivityIndexDescriptor rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:FmfDescriptor rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:Fsp3 rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:FragmentComplexityDescriptor rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:PetitjeanNumber rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:LipinskiRuleOf5Failures rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:WienerPathNumber rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:Xlogp rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:ZagrebIndex rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.

coconut:TopoPSA rdf:type owl:DatatypeProperty;
  rdfs:domain :MolecularDescriptors ;
  rdfs:range xsd:float ;
  dct:issued "2022-06-07"^^xsd:date ;
  rdfs:label ""@en
.


